/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.astuetz.viewpager.extensions;

public final class R {
    public static final class attr {

        public static final class styleable {
            public static final int[] PagerSlidingTabStrip = {
                    0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003,
                    0x7f010004, 0x7f010005, 0x7f010006, 0x7f010007,
                    0x7f010008, 0x7f010009, 0x7f01000a
            };
        }
    }
}
