/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.astuetz.viewpager.extensions;

public final class R {
    public static final class attr {
        /**
         * <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
         * "<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         */
        public static int dividerColor = 0x7f010002;
        /**
         * <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
         * Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
         * in (inches), mm (millimeters).
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         */
        public static int dividerPadding = 0x7f010005;
        /**
         * <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
         * "<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         */
        public static int indicatorColor = 0x7f010000;
        /**
         * <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
         * Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
         * in (inches), mm (millimeters).
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         */
        public static int indicatorHeight = 0x7f010003;
        /**
         * <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
         * Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
         * in (inches), mm (millimeters).
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         */
        public static int scrollOffset = 0x7f010007;
        /**
         * <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         */
        public static int shouldExpand = 0x7f010009;
        /**
         * <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
         * or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int tabBackground = 0x7f010008;
        /**
         * <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
         * Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
         * in (inches), mm (millimeters).
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         */
        public static int tabPaddingLeftRight = 0x7f010006;
        /**
         * <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         */
        public static int textAllCaps = 0x7f01000a;
        /**
         * <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
         * "<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         */
        public static int underlineColor = 0x7f010001;
        /**
         * <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
         * Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
         * in (inches), mm (millimeters).
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         */
        public static int underlineHeight = 0x7f010004;
    }

    public static final class color {
        public static int background_tab_pressed = 0x7f030000;
    }

    public static final class drawable {
        public static int background_tab = 0x7f020000;
        public static int ic_launcher = 0x7f020001;
    }

    public static final class string {
        public static int app_name = 0x7f040000;
    }

    public static final class styleable {
        /**
         * Attributes that can be used with a PagerSlidingTabStrip.
         * <p>Includes the following attributes:</p>
         * <table>
         * <colgroup align="left" />
         * <colgroup align="left" />
         * <tr><th>Attribute</th><th>Description</th></tr>
         * <tr><td><code>{@link #PagerSlidingTabStrip_dividerColor com.astuetz.viewpager.extensions:dividerColor}</code></td><td></td></tr>
         * <tr><td><code>{@link #PagerSlidingTabStrip_dividerPadding com.astuetz.viewpager.extensions:dividerPadding}</code></td><td></td></tr>
         * <tr><td><code>{@link #PagerSlidingTabStrip_indicatorColor com.astuetz.viewpager.extensions:indicatorColor}</code></td><td></td></tr>
         * <tr><td><code>{@link #PagerSlidingTabStrip_indicatorHeight com.astuetz.viewpager.extensions:indicatorHeight}</code></td><td></td></tr>
         * <tr><td><code>{@link #PagerSlidingTabStrip_scrollOffset com.astuetz.viewpager.extensions:scrollOffset}</code></td><td></td></tr>
         * <tr><td><code>{@link #PagerSlidingTabStrip_shouldExpand com.astuetz.viewpager.extensions:shouldExpand}</code></td><td></td></tr>
         * <tr><td><code>{@link #PagerSlidingTabStrip_tabBackground com.astuetz.viewpager.extensions:tabBackground}</code></td><td></td></tr>
         * <tr><td><code>{@link #PagerSlidingTabStrip_tabPaddingLeftRight com.astuetz.viewpager.extensions:tabPaddingLeftRight}</code></td><td></td></tr>
         * <tr><td><code>{@link #PagerSlidingTabStrip_textAllCaps com.astuetz.viewpager.extensions:textAllCaps}</code></td><td></td></tr>
         * <tr><td><code>{@link #PagerSlidingTabStrip_underlineColor com.astuetz.viewpager.extensions:underlineColor}</code></td><td></td></tr>
         * <tr><td><code>{@link #PagerSlidingTabStrip_underlineHeight com.astuetz.viewpager.extensions:underlineHeight}</code></td><td></td></tr>
         * </table>
         *
         * @see #PagerSlidingTabStrip_dividerColor
         * @see #PagerSlidingTabStrip_dividerPadding
         * @see #PagerSlidingTabStrip_indicatorColor
         * @see #PagerSlidingTabStrip_indicatorHeight
         * @see #PagerSlidingTabStrip_scrollOffset
         * @see #PagerSlidingTabStrip_shouldExpand
         * @see #PagerSlidingTabStrip_tabBackground
         * @see #PagerSlidingTabStrip_tabPaddingLeftRight
         * @see #PagerSlidingTabStrip_textAllCaps
         * @see #PagerSlidingTabStrip_underlineColor
         * @see #PagerSlidingTabStrip_underlineHeight
         */
        public static final int[] PagerSlidingTabStrip = {
                0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003,
                0x7f010004, 0x7f010005, 0x7f010006, 0x7f010007,
                0x7f010008, 0x7f010009, 0x7f01000a
        };
        /**
         * <p>This symbol is the offset where the {@link com.astuetz.viewpager.extensions.R.attr#dividerColor}
         * attribute's value can be found in the {@link #PagerSlidingTabStrip} array.
         * <p/>
         * <p/>
         * <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
         * "<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         *
         * @attr name com.astuetz.viewpager.extensions:dividerColor
         */
        public static final int PagerSlidingTabStrip_dividerColor = 2;
        /**
         * <p>This symbol is the offset where the {@link com.astuetz.viewpager.extensions.R.attr#dividerPadding}
         * attribute's value can be found in the {@link #PagerSlidingTabStrip} array.
         * <p/>
         * <p/>
         * <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
         * Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
         * in (inches), mm (millimeters).
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         *
         * @attr name com.astuetz.viewpager.extensions:dividerPadding
         */
        public static final int PagerSlidingTabStrip_dividerPadding = 5;
        /**
         * <p>This symbol is the offset where the {@link com.astuetz.viewpager.extensions.R.attr#indicatorColor}
         * attribute's value can be found in the {@link #PagerSlidingTabStrip} array.
         * <p/>
         * <p/>
         * <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
         * "<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         *
         * @attr name com.astuetz.viewpager.extensions:indicatorColor
         */
        public static final int PagerSlidingTabStrip_indicatorColor = 0;
        /**
         * <p>This symbol is the offset where the {@link com.astuetz.viewpager.extensions.R.attr#indicatorHeight}
         * attribute's value can be found in the {@link #PagerSlidingTabStrip} array.
         * <p/>
         * <p/>
         * <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
         * Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
         * in (inches), mm (millimeters).
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         *
         * @attr name com.astuetz.viewpager.extensions:indicatorHeight
         */
        public static final int PagerSlidingTabStrip_indicatorHeight = 3;
        /**
         * <p>This symbol is the offset where the {@link com.astuetz.viewpager.extensions.R.attr#scrollOffset}
         * attribute's value can be found in the {@link #PagerSlidingTabStrip} array.
         * <p/>
         * <p/>
         * <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
         * Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
         * in (inches), mm (millimeters).
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         *
         * @attr name com.astuetz.viewpager.extensions:scrollOffset
         */
        public static final int PagerSlidingTabStrip_scrollOffset = 7;
        /**
         * <p>This symbol is the offset where the {@link com.astuetz.viewpager.extensions.R.attr#shouldExpand}
         * attribute's value can be found in the {@link #PagerSlidingTabStrip} array.
         * <p/>
         * <p/>
         * <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         *
         * @attr name com.astuetz.viewpager.extensions:shouldExpand
         */
        public static final int PagerSlidingTabStrip_shouldExpand = 9;
        /**
         * <p>This symbol is the offset where the {@link com.astuetz.viewpager.extensions.R.attr#tabBackground}
         * attribute's value can be found in the {@link #PagerSlidingTabStrip} array.
         * <p/>
         * <p/>
         * <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
         * or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         *
         * @attr name com.astuetz.viewpager.extensions:tabBackground
         */
        public static final int PagerSlidingTabStrip_tabBackground = 8;
        /**
         * <p>This symbol is the offset where the {@link com.astuetz.viewpager.extensions.R.attr#tabPaddingLeftRight}
         * attribute's value can be found in the {@link #PagerSlidingTabStrip} array.
         * <p/>
         * <p/>
         * <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
         * Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
         * in (inches), mm (millimeters).
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         *
         * @attr name com.astuetz.viewpager.extensions:tabPaddingLeftRight
         */
        public static final int PagerSlidingTabStrip_tabPaddingLeftRight = 6;
        /**
         * <p>This symbol is the offset where the {@link com.astuetz.viewpager.extensions.R.attr#textAllCaps}
         * attribute's value can be found in the {@link #PagerSlidingTabStrip} array.
         * <p/>
         * <p/>
         * <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         *
         * @attr name com.astuetz.viewpager.extensions:textAllCaps
         */
        public static final int PagerSlidingTabStrip_textAllCaps = 10;
        /**
         * <p>This symbol is the offset where the {@link com.astuetz.viewpager.extensions.R.attr#underlineColor}
         * attribute's value can be found in the {@link #PagerSlidingTabStrip} array.
         * <p/>
         * <p/>
         * <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
         * "<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         *
         * @attr name com.astuetz.viewpager.extensions:underlineColor
         */
        public static final int PagerSlidingTabStrip_underlineColor = 1;
        /**
         * <p>This symbol is the offset where the {@link com.astuetz.viewpager.extensions.R.attr#underlineHeight}
         * attribute's value can be found in the {@link #PagerSlidingTabStrip} array.
         * <p/>
         * <p/>
         * <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
         * Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
         * in (inches), mm (millimeters).
         * <p>This may also be a reference to a resource (in the form
         * "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
         * theme attribute (in the form
         * "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
         * containing a value of this type.
         *
         * @attr name com.astuetz.viewpager.extensions:underlineHeight
         */
        public static final int PagerSlidingTabStrip_underlineHeight = 4;
    }

    ;
}
